### ISSUE TITLE
How to generate "vqa-resnet-14x14.h5"?

### ISSUE THREAD

**Issue by BA3000** [hexiang-hu/answer_embedding#1]
The training process requires file "vqa-resnet-14x14.h5", how it is generated?

**Comment by BA3000** [comment]
It seems that the `preprocess-images.py` from `pytorch-vqa` repo is relevant to the generation of "vqa-resnet-14x14.h5". I used the "resnet-14x14.h5" generated with the script just mentioned for training, and it works.

**Comment by hexiang-hu** [comment]
Thanks for the nice catch! It seems like I forget to upload the scripts to extract features... I will upload this later but what you did is basically the exact thing that happened. 

The feature extraction code is adapted from ``pytorch-vqa``, which I directly used for VQA/VQA2  datasets, and visual genome and visual7w.
